/*
DESAFIOS FUNDAMENTOS SQL

1 - QUANTOS PRODUTOS TEMOS CADASTRADO NO SISTEMA QUE CUSTAM MAIS QUE 1500 DOLARES? R: 39
*/
SELECT	COUNT(ListPrice)
FROM	Production.Product
WHERE	ListPrice > 1500;

/*
2 - QUANTAS PESSOAS TEMOS COM O SOBRENOME QUE INICIA COM A LETRA P? R: 1.187
*/
SELECT	COUNT(LastName)
FROM	Person.Person
WHERE	LastName LIKE 'P%';

/*
3 - EM QUANTAS CIDADES ÚNICAS ESTÃO CADASTRADOS NOSSOS CLIENTES? R: 575
*/
SELECT	COUNT(DISTINCT City)
FROM	Person.Address;

/*
4 - QUAIS SÃO AS CIDADES ÚNICAS QUE TEMOS CADASTRADOS EM NOSSO SISTEMA? R: 575
*/
SELECT	DISTINCT City
FROM	Person.Address;

/*
5 - QUANTOS PRODUTOS VERMELHOS TEM O PREÇO ENTRE 500 A 100 DOLARES? R: 11
*/
SELECT	*
FROM	Production.Product
WHERE Color = 'Red'
AND ListPrice BETWEEN 500 AND 1000;

/*
6 - QUANTOS PRODUTOS CADASTRADOS TEM A PALAVRA 'ROAD' NO NOME DELES?
*/
SELECT	COUNT(*)
FROM	Production.Product
WHERE	Name LIKE '%road%';