/*
SELECT

SELECT  *
FROM    tabela;

### DESAFIO 1 ###

A EQUIPE DE MARKETING PRECISA FAZER UMA PESQUISA SOBRE NOMES MAIS COMUNS DE SEUS CLIENTES
E PRECISA DO NOME E SOBRENOME DE TODOS OS CLIENTES QUE ESTÃO CADASTRADOS NO SISTEMA.
*/

SELECT FirstName, LastName
FROM Person.Person;