-- SELF JOIN

--SELECT	NOME_COLUNA
--FROM	TABELA A, TABELA B
--WHERE	CONDICAO

-- BUSCAR TODOS OS CLIENTES QUE MORAM NA MESMA REGIÃO

SELECT	A.ContactName, A.Region, B.ContactName, B.Region
FROM	Customers AS A, Customers AS B
WHERE	A.Region = B.Region;

-- ENCONTRAR NOME E DATA DE CONTRATAÇÃO DE TODOS OS FUNCIONÁRIOS QUE FORAM CONTRATADOS NO MESMO ANO
SELECT	A.FirstName, A.HireDate,B.FirstName,B.HireDate
FROM	Employees AS A, Employees AS B
WHERE	DATEPART(YEAR,A.HireDate) = DATEPART(YEAR,B.HireDate);

-- NA TABELA DETALHE DE PEDIDOS [ORDER DETAILS] QUAIS PRODUTOS TEM O MESMO PERCENTUAL DE DESCOTNO
SELECT	A.ProductID, A.Discount, B.ProductID, B.Discount
FROM	[Order Details] AS A, [Order Details] AS B
WHERE	A.Discount = B.Discount;
