-- ALTER TABLE

CREATE TABLE Youtube(
id			INT				PRIMARY KEY,
Nome		VARCHAR(150)	NOT NULL UNIQUE,
Categoria	VARCHAR(200)	NOT NULL,
DataCriacao	DATETIME		NOT NULL,
);

SELECT *
FROM Youtube

-- ADICIONAR UMA NOVA COLUNA
ALTER TABLE Youtube
ADD Ativo BIT;

-- ALTERAR O LIMITE DE UMA COLUNA
ALTER TABLE Youtube
ALTER COLUMN Categoria VARCHAR(300) NOT NULL;

-- ALTERAR O NOME DE UMA COLUNA
-- PROCEDURE ESPECÍFICA
EXEC sp_RENAME 'Youtube.Nome', 'NomeCanal', 'COLUMN'

-- ALTERAR O NOME DE UMA TABELA
-- PROCEDURE ESPECÍFICA
EXEC sp_rename 'Youtube', 'Youtube2'

