/*
DESAFIOS HAVING - INTERMEDIÁRIO

SELECT  coluna1, funcaoAgregacao(coluna2)
FROM    tabela
GROUP BY    coluna1
HAVING condicao; 

*/

-- Quais os nomes no sisterma tem uma ocorrencia maior que 10 vezes

SELECT  FirstName, COUNT(FirstName) AS 'QUANTIDADE'
FROM    Person.Person
GROUP BY	FirstName
HAVING COUNT(FirstName) > 10;

-- QUAIS PRODUTOS QUE NO TOTAL DE VENDAS ESTÃO ENTRE 162K A 500K

SELECT TOP 10 *
FROM Sales.SalesOrderDetail;

SELECT	ProductID, SUM(LineTotal) AS 'TOTAL'
FROM	Sales.SalesOrderDetail
GROUP BY	ProductID
HAVING	SUM(LineTotal) BETWEEN 162000 AND 500000
ORDER BY	TOTAL DESC;

-- Quais os nomes no sisterma tem uma ocorrencia maior que 10 vezes, PORÉM SOMENTE ONDE O TITLE É MS.

SELECT  FirstName, COUNT(FirstName) AS 'QUANTIDADE'
FROM    Person.Person
WHERE Title = 'mr.'
GROUP BY	FirstName
HAVING COUNT(FirstName) > 10;

-- DESAFIO 1 - ESTAMOS QUERENDO IDENTIFICAR AS PROVÍNCIAS(STATEPROVINCEID) COM O MAIOR NÚMERO DE CADASTRO NO NOSSO SISTEMA,
-- ENTÃO É PRECISO ENCONTRAR QUAIS PROVÍNCIAS(STATEPROVINCEID) ESTÃO REGISTRADAS NO BANCO DE DADOS MAIS QUE 1000 VEZES

SELECT	StateProvinceID, COUNT(StateProvinceID) AS 'QUANTIDADE'
FROM	Person.Address
GROUP BY StateProvinceID
HAVING COUNT(StateProvinceID) > 1000;

-- DESAFIO 2 - OS GERENTES DE UMA MULTINACIONAL QUEREM SABER QUAIS PRODUTOS (PRODUCTID) 
-- NÃO ESTÃO TRAZENDO EM MÉDIA NO MÍNIMO 1 MILHÃO EM TOTAL DE VENDAS (LINETOTAL)

SELECT	ProductID, AVG(LineTotal) AS 'MEDIA'
FROM	Sales.SalesOrderDetail
GROUP BY ProductID
HAVING AVG(LineTotal) < 1000000
ORDER BY MEDIA DESC;
