/*
DESAFIOS GROUP BY

SELECT  coluna1, funcaoAgregacao(coluna2)
FROM    tabela
GROUP BY    coluna1

*/

SELECT	*
FROM	Sales.SalesOrderDetail;

SELECT	SpecialOfferID, UnitPrice
FROM	Sales.SalesOrderDetail
WHERE	SpecialOfferID = 9;

SELECT SpecialOfferID, SUM(UnitPrice) AS 'SOMA'
FROM	Sales.SalesOrderDetail
GROUP BY	SpecialOfferID;

-- QUANTO DE CADA PRODUTO FOI VENDIDO ATÉ HOJE?
SELECT	ProductID, COUNT(ProductID)
FROM	Sales.SalesOrderDetail
GROUP BY ProductID;

-- QUANTOS NOMES DE CADA NOME TEMOS CADASTRADOS EM NOSSO BANCO DE DADOS?
SELECT	FirstName, COUNT(FirstName) AS 'CONTAGEM'
FROM	Person.Person
GROUP BY FirstName;

-- NA TABELA PRODUCTION.PRODUCT QUAL A MÉDIA DE PREÇO PARA OS PRODUTOS QUE SÃO PRATAS(SILVER)?
SELECT	Color, AVG(ListPrice) AS 'MEDIA'
FROM	Production.Product
WHERE color = 'Silver'
GROUP BY	Color;

-- DESAFIO 1 - QUANTAS PESSOAS TEM O MESMO MIDDLENAME AGRUPADAS POR O MIDDLENAME
SELECT	MiddleName, COUNT(MiddleName) AS 'QUANTIDADE'
FROM	Person.Person
GROUP BY MiddleName;

-- DESAFIO 2 - EM MÉDIA QUAL É A QUANTIDADE(QUANTITY) QUE CADA PRODUTO É VENDIDO NA LOJA
SELECT	ProductID, AVG(OrderQty) AS 'MEDIA'
FROM	Sales.SalesOrderDetail
GROUP BY	ProductID;

-- DESAFIO 3 - QUAIS FORAM AS 10 VENDAS QUE NO TOTAL TIVERAM OS MAIORES VALORES DE VENDA (LINE TOTAL) POR PRODUTO DO MAIOR VALOR PARA O MENOR
SELECT	TOP 10 ProductID, SUM(LineTotal) AS 'VALOR'
FROM	Sales.SalesOrderDetail
GROUP BY ProductID
ORDER BY VALOR DESC;

-- DESAFIO 4 - QUANTOS PRODUTOS E QUAL A QUANTIDADE MÉDIA DE PRODUTOS TEMOS CADASTRADOS NAS NOSSAS ORDEM DE SERVIÇO (WORKORDER),
-- AGRUPADOS POR PRODUCTID
SELECT	ProductID, COUNT(ProductID) AS 'QUANTIDADE', AVG(OrderQty) AS 'MEDIA'
FROM	Production.WorkOrder
GROUP BY ProductID;